apiVersion: v2
name: logging-helm
description: This is a helm chart for logging related tasks for starchat
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: "http://minio-service.triton-inference-services.svc.cluster.local:9000/helm-storage/starchat/logging/helm-icon.png"