apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.application.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
        - name: {{ .Values.application.name }}
          image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag }}"
          ports:
            - containerPort: {{ .Values.application.ports.containerPort }}
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
          env:
            - name: CLIENT_ID
              value: "{{ .Values.application.env.CLIENT_ID }}"
            - name: CLIENT_SECRET
              value: "{{ .Values.application.env.CLIENT_SECRET }}"
            - name: KEYCLOAK_URL
              value: "{{ .Values.application.env.KEYCLOAK_URL }}"
            - name: REALM
              value: "{{ .Values.application.env.REALM }}"
            - name: REDIRECT_URI
              value: "{{ .Values.application.env.REDIRECT_URI }}"
            - name: OLLAMA_MODEL_NAME
              value: "{{ .Values.application.env.OLLAMA_MODEL_NAME }}"
            - name: VLLM_MODEL_NAME
              value: "{{ .Values.application.env.VLLM_MODEL_NAME }}"
            - name: OLLAMA_MODEL_BASE_URL
              value: "{{ .Values.application.env.OLLAMA_MODEL_BASE_URL }}"
            - name: VLLM_MODEL_BASE_URL
              value: "{{ .Values.application.env.VLLM_MODEL_BASE_URL }}"
            - name: LLM_PROVIDER
              value: "{{ .Values.application.env.LLM_PROVIDER }}"
            - name: LOGGING_URL
              value: "{{ .Values.application.env.LOGGING_URL }}"
            - name: LOGGING
              value: "{{ .Values.application.env.LOGGING }}"
            - name: VLLM_FULL_MODEL
              value: "{{ .Values.application.env.VLLM_FULL_MODEL }}"