apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.routeApplication.name }}
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.application.name }}
  port:
    targetPort: {{ .Values.application.ports.containerPort }}
  tls:
    termination: {{ .Values.routeApplication.tlsTermination }}
  wildcardPolicy: {{ .Values.routeApplication.wildcardPolicy }}
