apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.explorer.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.explorer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.explorer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.explorer.name }}
    spec:
      containers:
        - name: {{ .Values.explorer.name }}
          image: "{{ .Values.explorer.image.repository }}:{{ .Values.explorer.image.tag }}"
          ports:
            - containerPort: {{ .Values.explorer.ports.containerPort }}
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
          env:
            - name: PYTHON_ENV
              value: "{{ .Values.explorer.env.lol }}"
            - name: DATABASE_URL
              value: "{{ .Values.explorer.env.lol }}"
