apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.explorer.route.name }}
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.explorer.route.name }}
  port:
    targetPort: {{ .Values.explorer.ports.containerPort }}
  tls:
    termination: {{ .Values.explorer.route.tlsTermination }}
  wildcardPolicy: {{ .Values.explorer.route.wildcardPolicy }}
