# values.yaml

# Namespace for the resources
namespace: starchat

# Application settings for "application"
application:
  name: application
  image:
    repository: quay.io/jeslynlamxy/starchat-app
    tag: latest
  replicas: 1
  ports:
    containerPort: 8501 # Application's container port

# Application settings for "explorer"
explorer:
  name: explorer
  image:
    repository: quay.io/jeslynlamxy/explorer-app
    tag: latest
  replicas: 1
  ports:
    containerPort: 8501 # Explorer's container port

# Application settings for "logging"
logging:
  name: logging
  image:
    repository: quay.io/jeslynlamxy/postgres-logging
    tag: latest
  replicas: 1
  ports:
    containerPort: 5432 # Logging application's container port
  env:
    postgresUser: user
    postgresPassword: pass
    postgresDb: database
  securityContext:
    runAsUser: 1000970000
    fsGroup: 1000970000
  storage:
    request: "1Gi"
    limit: "10Gi"
    persistentVolumeClaim:
      storageRequest: 20Gi
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      hostPath: /mnt/data/logging-pv

# Application settings for "model"
model:
  name: model
  image:
    repository: quay.io/jeslynlamxy/ollama-llama-8b
    tag: latest
  replicas: 1
  ports:
    containerPort: 11434 # Model's container port
  resources:
    requests:
      nvidia.com/gpu: 1 # Request 1 GPU
      cpu: "2"
      memory: "20Gi"
    limits:
      nvidia.com/gpu: 1 # Limit to 1 GPU
      cpu: "4"
      memory: "32Gi"

# Container resource settings (shared across applications)
resources:
  requests:
    cpu: "0.5"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

# Route settings for "application" (OpenShift)
routeApplication:
  name: application-route
  tlsTermination: edge
  wildcardPolicy: None

# Route settings for "explorer" (OpenShift)
routeExplorer:
  name: explorer-route
  tlsTermination: edge
  wildcardPolicy: None
