apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
  namespace: starchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
        - name: explorer
          image: quay.io/jeslynlamxy/explorer-app:latest
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: explorer
  namespace: starchat
spec:
  selector:
    app: explorer
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: explorer-route
  namespace: starchat
spec:
  to:
    kind: Service
    name: explorer
  port:
    targetPort: 8501
  tls:
    termination: edge
  wildcardPolicy: None
