apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-pvc
  namespace: starchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
  namespace: starchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      securityContext:
        runAsUser: 1000970000 # Updated to a valid user ID
        fsGroup: 1000970000 # Updated to a valid group ID
      containers:
        - name: logging
          image: quay.io/jeslynlamxy/postgres-logging:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "pass"
            - name: POSTGRES_DB
              value: "database"
          resources:
            requests:
              ephemeral-storage: "1Gi" # Request for ephemeral storage
            limits:
              ephemeral-storage: "10Gi" # Limit for ephemeral storage
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: logging-storage
      volumes:
        - name: logging-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: logging
  namespace: starchat
spec:
  selector:
    app: logging
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
