apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: starchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: quay.io/jeslynlamxy/starquery-app:latest
        ports:
          - containerPort: 8501
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: starchat
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: streamlit-route
  namespace: starchat
spec:
  to:
    kind: Service
    name: streamlit
  port:
    targetPort: 8501
  tls:
    termination: edge
  wildcardPolicy: None